### PR TITLE
Migrate to ESM and ECMA2022 (second attempt)

### LINKED ISSUE #179: Cannot find module './dist/server/server'
After a clean clone / npm install I get:

```sh
...
> saxi@0.16.0 build:ui
> node --experimental-modules build.mjs


  dist/ui/ui.js                              322.6kb
  dist/ui/ui.css                               5.5kb
  dist/ui/path-joining radius-IQOHHOQE.svg     479b 
  dist/ui/point-joining radius-7FJFFNS3.svg    407b 
  dist/ui/rotate-drawing-N3MHMTY3.svg          395b 
  dist/ui/ui.js.map                            1.2mb
  dist/ui/ui.css.map                          12.1kb

⚡ Done in 50ms

  dist/ui/index.html - 286
  HTML Plugin Done in 38ms
node:internal/modules/esm/resolve:275
    throw new ERR_MODULE_NOT_FOUND(
          ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/julian.badillo/Documents/workspace/saxi/dist/server/server' imported from /Users/julian.badillo/Documents/workspace/saxi/dist/server/cli.js
    at finalizeResolution (node:internal/modules/esm/resolve:275:11)
    at moduleResolve (node:internal/modules/esm/resolve:860:10)
    at defaultResolve (node:internal/modules/esm/resolve:984:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:719:12)
    at #cachedDefaultResolve (node:internal/modules/esm/loader:643:25)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:626:38)
    at ModuleLoader.getModuleJobForImport (node:internal/modules/esm/loader:279:38)
    at ModuleJob._link (node:internal/modules/esm/module_job:136:49) {
  code: 'ERR_MODULE_NOT_FOUND',
  url: 'file:///Users/julian.badillo/Documents/workspace/saxi/dist/server/server'
}

Node.js v23.7.0
```

### PR DESCRIPTION
**Pull request by alexrudd2**
Closes #179

Better attempt at https://github.com/alexrudd2/saxi/pull/178 which had to be reverted.

`npm run dev`, `npm run start`, and `npm run dev` all work for me, but I didn't try with `IS_WEB`

### CODE REVIEW

**Comment by juli4nb4dillo** [comment]
I'll try better on the afternoon, but on a clean install, on clean build and `npm start` I get:

Screenshot 2025-03-03 at 8 18 08 AM

So it doesn't find static assets.

`npm run dev` works fine though.

Web mode only also seems to work fine.

**Comment by alexrudd2** [comment]
bisected to 6454b66120d8821b42ab46654a1fdf7f2f0e768e

**Comment by alexrudd2** [comment]
@juli4nb4dillo  I think I got it this time.  Try again?

**Comment by alexrudd2** [comment]
Ok _this time_ is totally different I swear :)

**Comment by juli4nb4dillo** [comment]
Works now.

**Review by juli4nb4dillo — APPROVED** [review]
I tested the three modes (start / dev / web)
